name: VSTO

on:
  workflow_dispatch:
    branches: [ master ]
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug]
        targetplatform: [x64]

    runs-on: windows-latest

    env:
      Solution_Name: ScreenCapture.sln                            

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore packages
    - name: Restore packages
      run: msbuild $env:Solution_Name -restore

    # Build the Application
    - name: Build Application
      run: msbuild $env:Solution_Name
